global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gesture_app'
    static_configs:
      - targets: ['172.25.70.243:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']





