global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gesture_control'
    static_configs:
      - targets: ['gui_app:8000']

  - job_name: 'environment_analysis'
    static_configs:
      - targets: ['gui_app:8001']

  - job_name: 'drowsiness_detection'
    static_configs:
      - targets: ['gui_app:8002']

  - job_name: 'merging_gui'
    static_configs:
      - targets: ['gui_app:8003']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']





