services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  gui_app:
    build: ./gui_app
    container_name: gui_app
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    # These volume mounts don't work on Windows, so they're commented out or modified
    # cadvisor will run, but with limited functionality on Windows
    #volumes:
    #  - /:/rootfs:ro
    #  - /var/run:/var/run:ro
    #  - /sys:/sys:ro
    #  - /var/lib/docker/:/var/lib/docker:ro
    #  - /dev/disk/:/dev/disk:ro
    #privileged: true

volumes:
  grafana-storage:
