services:
  consumer:
    image: mqtt_consumer
    container_name: consumer
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.consumer
    networks:
      - mqtt-net


networks:
  mqtt-net:
    name: mqtt-net